TITLE = "Measures of Spread"

SECTIONS = [
    {
        "title": "Why Spread Matters: Beyond the Average",
        "body": "<div class='concept-box'><p>Knowing the average is useful, but it doesn't tell the whole story. Two datasets can have the same mean but be very different.</p></div><h3>Example: Two Classes' Test Scores</h3><div class='example-box'><p><strong>Class A:</strong> 75, 78, 80, 82, 85 → Mean = 80</p><p><strong>Class B:</strong> 45, 65, 80, 95, 115 → Mean = 80</p><p>Same mean (80), but very different! Class A scores cluster around 80. Class B has wild variation from 45 to 115.</p><p><strong>Spread measures tell us how spread out (or clustered) data is.</strong></p></div><h3>Three Key Measures of Spread</h3><ul><li><strong>Range:</strong> Difference between highest and lowest</li><li><strong>Interquartile Range (IQR):</strong> Spread of the middle 50%</li><li><strong>Standard Deviation:</strong> Average distance from the mean</li></ul>"
    },
    {
        "title": "The Range: Simplest Spread Measure",
        "body": "<h3>Definition and Formula</h3><p>\\(\\text{Range} = x_{max} - x_{min}\\)</p><p>The <strong>range</strong> is the difference between the highest and lowest values.</p><h3>Example 1: Simple Range</h3><div class='example-box'><p><strong>Test scores: 45, 62, 78, 89, 91</strong></p><p>Highest: 91</p><p>Lowest: 45</p><p>Range = 91 - 45 = 46</p></div><h3>Example 2: Comparing Data</h3><div class='example-box'><p><strong>Class A temperatures:</strong> 19, 20, 21, 22, 23°C</p><p>Range = 23 - 19 = 4°C (temperatures stable)</p><p><strong>Class B temperatures:</strong> 5, 15, 20, 25, 30°C</p><p>Range = 30 - 5 = 25°C (temperatures vary widely)</p></div><h3>Limitations of Range</h3><div class='example-box'><p><strong>Data A:</strong> 10, 11, 12, 13, 14 → Range = 4 (data clustered)</p><p><strong>Data B:</strong> 10, 14, 14, 14, 14 → Range = 4 (one high value, rest at 14)</p><p>Same range, but distribution is very different!</p><p><strong>Range only tells us about the extremes, not the middle.</strong></p></div><div class='success-box'><p><strong>When to use range:</strong> Quick, simple comparison; but beware—outliers can make range large even if most data is clustered.</p></div>"
    },
    {
        "title": "Quartiles and the Interquartile Range (IQR)",
        "body": "<h3>What Are Quartiles?</h3><p>Just as the median divides data into two halves, <strong>quartiles</strong> divide data into four quarters.</p><ul><li><strong>Q1 (First Quartile):</strong> 25th percentile—25% of data below this, 75% above</li><li><strong>Q2 (Second Quartile):</strong> 50th percentile—this is the median</li><li><strong>Q3 (Third Quartile):</strong> 75th percentile—75% of data below this, 25% above</li></ul><h3>Example: Finding Quartiles</h3><div class='example-box'><p><strong>Data (ordered): 2, 4, 6, 8, 10, 12, 14, 16</strong></p><p>Q1 (median of lower half): (4 + 6) ÷ 2 = 5</p><p>Q2 (median of all): (8 + 10) ÷ 2 = 9</p><p>Q3 (median of upper half): (12 + 14) ÷ 2 = 13</p></div><h3>Interquartile Range (IQR)</h3><p>\\(IQR = Q3 - Q1\\)</p><p>The <strong>IQR</strong> is the range of the middle 50% of data. It ignores the top 25% and bottom 25%, so outliers don't affect it.</p><div class='example-box'><p>From above: IQR = 13 - 5 = 8</p><p>This tells us the middle 50% of data spans a range of 8.</p></div><h3>IQR vs. Range</h3><div class='example-box'><p><strong>Data with outliers: 2, 4, 6, 8, 10, 12, 14, 500</strong></p><p>Range = 500 - 2 = 498 (outlier makes it huge!)</p><p>Q1 = 5, Q3 = 13, IQR = 8 (unaffected by the 500 outlier)</p><p><strong>IQR is more reliable when outliers exist.</strong></p></div><div class='success-box'><p><strong>When to use IQR:</strong> Better than range; ignores extreme outliers; good for skewed data.</p></div>"
    },
    {
        "title": "Five-Number Summary and Box-and-Whisker Plots",
        "body": "<h3>The Five-Number Summary</h3><p>A complete picture of spread uses five numbers:</p><ol><li><strong>Minimum:</strong> Smallest value</li><li><strong>Q1:</strong> First quartile (25th percentile)</li><li><strong>Q2 (Median):</strong> Middle value</li><li><strong>Q3:</strong> Third quartile (75th percentile)</li><li><strong>Maximum:</strong> Largest value</li></ol><h3>Example</h3><div class='example-box'><p><strong>Data: 2, 4, 6, 8, 10, 12, 14, 16</strong></p><ul><li>Minimum: 2</li><li>Q1: 5</li><li>Q2 (Median): 9</li><li>Q3: 13</li><li>Maximum: 16</li></ul></div><h3>Box-and-Whisker Plot</h3><p>A <strong>box-and-whisker plot</strong> visually displays the five-number summary.</p><svg width='400' height='150' style='display: block; margin: 20px auto; ;'><text x='20' y='30' font-size='12' fill='#e6edf3'>Min=2 Q1=5 Q2=9 Q3=13 Max=16</text><line x1='40' y1='80' x2='360' y2='80' stroke='#e6edf3' stroke-width='2'/><circle cx='40' cy='80' r='5' fill='none' stroke='#e6edf3' stroke-width='2'/><rect x='80' y='60' width='120' height='40' fill='none' stroke='#e6edf3' stroke-width='2'/><line x1='130' y1='60' x2='130' y2='100' stroke='#e6edf3' stroke-width='2'/><circle cx='360' cy='80' r='5' fill='none' stroke='#e6edf3' stroke-width='2'/><text x='35' y='120' font-size='11' fill='#e6edf3'>Min</text><text x='75' y='120' font-size='11' fill='#e6edf3'>Q1</text><text x='120' y='120' font-size='11' fill='#e6edf3'>Median</text><text x='210' y='120' font-size='11' fill='#e6edf3'>Q3</text><text x='350' y='120' font-size='11' fill='#e6edf3'>Max</text></svg><h3>Reading a Box-and-Whisker Plot</h3><ul><li><strong>The box:</strong> Shows the middle 50% (Q1 to Q3)</li><li><strong>The line inside:</strong> Shows the median (Q2)</li><li><strong>The whiskers:</strong> Lines to min and max (show full range)</li><li><strong>Box width:</strong> If wide, middle 50% is spread out. If narrow, data is clustered.</li></ul><div class='success-box'><p><strong>Advantage:</strong> Box-and-whisker plots let you quickly compare multiple datasets and see outliers, clusters, and skewness at a glance.</p></div>"
    }
]
