# Concept 5: Decorators and Closures

TITLE = "Decorators and Closures"

SECTIONS = [
    {
        "id": "py_functions_05_01",
        "title": "Understanding Closures",
        "body": '<div class="concept-box"><h4>What is a Closure?</h4><p>A closure is a function that captures and remembers variables from its enclosing scope, even after the outer function has returned.</p></div><div class="worked-example"><h4>Simple Closure Example</h4><pre>def outer(x):\n    def inner():\n        print(f"x = {x}")  # inner remembers x\n    return inner\n\nfunc = outer(42)\nfunc()  # Output: x = 42\n\n# Even after outer() has finished, inner still knows x\nfunc()  # Output: x = 42</pre></div><h3>Closures with Mutable State</h3><p>Closures can maintain state between function calls.</p><div class="worked-example"><h4>Counter Closure</h4><pre>def make_counter():\n    count = 0\n\n    def increment():\n        nonlocal count  # Modify the outer count\n        count += 1\n        return count\n\n    return increment\n\ncounter = make_counter()\nprint(counter())  # Output: 1\nprint(counter())  # Output: 2\nprint(counter())  # Output: 3\n\n# Each closure has its own state\ncounter2 = make_counter()\nprint(counter2())  # Output: 1 (separate counter)</pre></div><h3>The nonlocal Keyword</h3><p>Use <code>nonlocal</code> to modify variables in an enclosing (not global) scope.</p><div class="concept-box"><h4>nonlocal vs. global</h4><ul><li><strong>global:</strong> Refers to module-level variables</li><li><strong>nonlocal:</strong> Refers to variables in the nearest enclosing scope</li></ul></div>'
    },
    {
        "id": "py_functions_05_02",
        "title": "Introduction to Decorators",
        "body": '<h3>What is a Decorator?</h3><p>A decorator is a function that modifies another function or class without permanently changing it. It is a way to "wrap" a function with additional functionality.</p><div class="concept-box"><h4>Decorator Pattern</h4><p>A decorator takes a function as input and returns a new function that enhances the original.</p></div><div class="worked-example"><h4>Basic Decorator Example</h4><pre>def my_decorator(func):\n    def wrapper():\n        print("Something before the function")\n        func()\n        print("Something after the function")\n    return wrapper\n\ndef say_hello():\n    print("Hello!")\n\n# Apply the decorator\nsay_hello = my_decorator(say_hello)\nsay_hello()\n\n# Output:\n# Something before the function\n# Hello!\n# Something after the function</pre></div><h3>The @ Syntax for Decorators</h3><p>Python provides syntactic sugar with the <code>@</code> symbol to apply decorators.</p><div class="worked-example"><h4>Using @ Decorator Syntax</h4><pre>def my_decorator(func):\n    def wrapper():\n        print("Before")\n        func()\n        print("After")\n    return wrapper\n\n@my_decorator\ndef say_hello():\n    print("Hello!")\n\nsay_hello()\n\n# Output:\n# Before\n# Hello!\n# After\n\n# This is equivalent to:\n# say_hello = my_decorator(say_hello)</pre></div>'
    },
    {
        "id": "py_functions_05_03",
        "title": "Decorators with Arguments and Return Values",
        "body": '<h3>Decorating Functions with Arguments</h3><p>To decorate functions that accept arguments, the wrapper must accept and pass them through.</p><div class="worked-example"><h4>Decorator for Functions with Arguments</h4><pre>def my_decorator(func):\n    def wrapper(*args, **kwargs):\n        print(f"Calling {func.__name__}")\n        result = func(*args, **kwargs)\n        print(f"{func.__name__} completed")\n        return result\n    return wrapper\n\n@my_decorator\ndef add(a, b):\n    return a + b\n\nresult = add(3, 5)\nprint(f"Result: {result}")\n\n# Output:\n# Calling add\n# add completed\n# Result: 8</pre></div><h3>Practical Decorator: Timing Functions</h3><p>A common use case is measuring how long a function takes to execute.</p><div class="worked-example"><h4>Timing Decorator</h4><pre>import time\n\ndef timing_decorator(func):\n    def wrapper(*args, **kwargs):\n        start = time.time()\n        result = func(*args, **kwargs)\n        elapsed = time.time() - start\n        print(f"{func.__name__} took {elapsed:.4f} seconds")\n        return result\n    return wrapper\n\n@timing_decorator\ndef slow_function(n):\n    time.sleep(n)\n    return f"Slept for {n} seconds"\n\nresult = slow_function(1)\n# Output: slow_function took 1.0001 seconds</pre></div>'
    },
    {
        "id": "py_functions_05_04",
        "title": "Advanced Decorators and Composition",
        "body": '<h3>Decorators with Parameters</h3><p>You can create decorators that accept parameters by adding another layer of nesting.</p><div class="worked-example"><h4>Parameterized Decorator</h4><pre>def repeat(times):\n    def decorator(func):\n        def wrapper(*args, **kwargs):\n            results = []\n            for _ in range(times):\n                result = func(*args, **kwargs)\n                results.append(result)\n            return results\n        return wrapper\n    return decorator\n\n@repeat(times=3)\ndef greet(name):\n    return f"Hello, {name}!"\n\nprint(greet("Alice"))\n# Output: ["Hello, Alice!", "Hello, Alice!", "Hello, Alice!"]</pre></div><h3>Stacking Multiple Decorators</h3><p>You can apply multiple decorators to the same function. They execute bottom-up.</p><div class="worked-example"><h4>Multiple Decorators</h4><pre>def uppercase_decorator(func):\n    def wrapper(*args, **kwargs):\n        result = func(*args, **kwargs)\n        return result.upper()\n    return wrapper\n\ndef exclaim_decorator(func):\n    def wrapper(*args, **kwargs):\n        result = func(*args, **kwargs)\n        return result + "!"\n    return wrapper\n\n@exclaim_decorator\n@uppercase_decorator\ndef greet(name):\n    return f"hello, {name}"\n\nprint(greet("alice"))\n# Output: HELLO, ALICE!\n# (uppercase applied first, then exclaim)</pre></div><h3>Using functools.wraps</h3><p>Decorators can lose function metadata. Use <code>functools.wraps</code> to preserve it.</p><div class="success-box"><h4>Proper Decorator with functools.wraps</h4><pre>import functools\n\ndef my_decorator(func):\n    @functools.wraps(func)  # Preserve function metadata\n    def wrapper(*args, **kwargs):\n        print(f"Calling {func.__name__}")\n        return func(*args, **kwargs)\n    return wrapper\n\n@my_decorator\ndef add(a, b):\n    """Add two numbers."""\n    return a + b\n\nprint(add.__name__)  # Output: add (not wrapper)\nprint(add.__doc__)  # Output: Add two numbers.</pre></div>'
    }
]
