SECTIONS = [
    {
        "title": "Open vs Closed Circles: Strict vs Non-Strict Inequalities",
        "body": "<h3>The Visual Language of Number Lines</h3><p>A number line shows all real numbers in order. To show an inequality solution, we use two visual markers:</p><ul><li><strong>Closed Circle ●</strong> — the point IS included (used for \\(\\leq\\) or \\(\\geq\\))</li><li><strong>Open Circle ○</strong> — the point is NOT included (used for < or >)</li></ul><div class='example-box'><h4>Section 1 Example: Open vs Closed</h4><p>\\(x > 3\\): Open circle at 3, arrow pointing right (all numbers GREATER than 3, but NOT 3 itself)</p><p>\\(x \\geq 3\\): Closed circle at 3, arrow pointing right (all numbers GREATER than or equal to 3, INCLUDING 3)</p><p>The difference is tiny visually, but huge mathematically: does the solution include 3 or not?</p></div><svg width='400' height='60' xmlns='http://www.w3.org/2000/svg'><rect width='400' height='60' fill='#161b22'/><line x1='20' y1='30' x2='380' y2='30' stroke='#e6edf3' stroke-width='2'/><circle cx='100' cy='30' r='6' fill='none' stroke='#e6edf3' stroke-width='2'/><line x1='106' y1='30' x2='380' y2='30' stroke='#e6edf3' stroke-width='3'/><text x='100' y='50' text-anchor='middle' fill='#e6edf3' font-size='12'>3</text><text x='200' y='20' fill='#e6edf3' font-size='13'>x > 3 (open circle)</text></svg>"
    },
    {
        "title": "Interval Notation: Translating Between Notations",
        "body": "<h3>Four Ways to Write Solutions</h3><p>Mathematicians use different notations for the same solution. They all mean the same thing!</p><table style='border-collapse: collapse; width: 100%; margin: 10px 0;'><tr style=';'><td style='padding: 8px;'><strong>Inequality</strong></td><td style='padding: 8px;'><strong>Number Line</strong></td><td style='padding: 8px;'><strong>Interval Notation</strong></td><td style='padding: 8px;'><strong>Description</strong></td></tr><tr style=';'><td style='padding: 8px;'>\\(x > 5\\)</td><td>Open at 5, right arrow</td><td>\\((5, \\infty)\\)</td><td>All x greater than 5</td></tr><tr style=';'><td style='padding: 8px;'>\\(x \\leq -2\\)</td><td>Closed at -2, left arrow</td><td>\\((-\\infty, -2]\\)</td><td>All x less than or equal to -2</td></tr><tr style=';'><td style='padding: 8px;'>\\(1 \\leq x < 4\\)</td><td>Closed at 1, open at 4, segment shaded</td><td>\\([1, 4)\\)</td><td>From 1 (including) to 4 (excluding)</td></tr></table><div class='example-box'><h4>Section 2 Example: Converting to Interval Notation</h4><p>Inequality: \\(-3 < x \\leq 8\\)</p><p>Number line: Open circle at -3, closed circle at 8, shaded between</p><p>Interval notation: \\((-3, 8]\\)</p><p>Memory aid: Parenthesis ( means OPEN, bracket [ means CLOSED</p></div>"
    },
    {
        "title": "Shaded Regions for Compound Solutions",
        "body": "<h3>Showing Multiple Regions on One Line</h3><p>Some solutions have gaps. For example, \\(x < 1\\) OR \\(x > 5\\) has TWO separate regions. We shade both on the same number line.</p><div class='example-box'><h4>Section 3 Example: Two Separate Regions</h4><p>Solution: \\(x \\leq -2\\) OR \\(x \\geq 4\\)</p><p>This includes all numbers to the left of -2 (including -2), AND all numbers to the right of 4 (including 4).</p><p>In interval notation: \\((-\\infty, -2] \\cup [4, \\infty)\\)</p><p>The symbol \\(\\cup\\) means union (combine both regions)</p></div><svg width='400' height='80' xmlns='http://www.w3.org/2000/svg'><rect width='400' height='80' fill='#161b22'/><line x1='20' y1='40' x2='380' y2='40' stroke='#e6edf3' stroke-width='2'/><line x1='20' y1='40' x2='120' y2='40' stroke='#4ade80' stroke-width='4'/><circle cx='120' cy='40' r='5' fill='none' stroke='#4ade80' stroke-width='2'/><line x1='280' y1='40' x2='380' y2='40' stroke='#4ade80' stroke-width='4'/><circle cx='280' cy='40' r='5' fill='none' stroke='#4ade80' stroke-width='2'/><text x='120' y='65' text-anchor='middle' fill='#e6edf3' font-size='12'>-2</text><text x='280' y='65' text-anchor='middle' fill='#e6edf3' font-size='12'>4</text><text x='200' y='20' fill='#e6edf3' font-size='13'>x ≤ -2 or x ≥ 4</text></svg>"
    },
    {
        "title": "Reading Solutions from Number Lines",
        "body": "<h3>Reverse Translation: From Visual to Notation</h3><p>Given a shaded number line, we must determine what inequality, interval notation, and description it represents.</p><div class='example-box'><h4>Section 4 Example: Analyzing a Given Line</h4><p>Visual: A number line with a closed circle at -1, shaded to the right to +2, with an open circle at +2.</p><p>Inequality: \\(-1 \\leq x < 2\\)</p><p>Interval: \\([-1, 2)\\)</p><p>English: All numbers from -1 to 2, including -1 but not including 2</p></div><p><strong>Reading Guide:</strong></p><ul><li>Closed circle = include endpoint (use bracket [)</li><li>Open circle = exclude endpoint (use parenthesis ()</li><li>Shaded segment = use \\(\\leq\\) or < between endpoints</li><li>Arrow to \\(\\infty\\) = use \\(\\infty\\) as the other endpoint</li></ul>"
    }
]
