SECTIONS = [
    {
        "title": "From Equations to Inequalities: The Sign Diagram Method",
        "body": "<h3>Why Linear Methods Don't Work for Quadratics</h3><p>You cannot simply divide a quadratic inequality like \\(x^2 > 4\\) by x. Instead, we use a visual sign-analysis method:</p><ol><li>Find the ROOTS (where the expression equals zero)</li><li>Create a sign diagram showing where the expression is positive or negative</li><li>Select the regions matching our inequality</li></ol><div class='example-box'><h4>Section 1 Example: Basic Quadratic Inequality</h4><p>Solve \\(x^2 - 4 > 0\\)</p><p><strong>Step 1:</strong> Factor: \\((x - 2)(x + 2) > 0\\)</p><p><strong>Step 2:</strong> Find roots: \\(x = 2\\) and \\(x = -2\\)</p><p><strong>Step 3:</strong> These roots divide the number line into THREE regions</p></div><svg width='400' height='100' xmlns='http://www.w3.org/2000/svg'><rect width='400' height='100' fill='#161b22'/><line x1='30' y1='50' x2='370' y2='50' stroke='#e6edf3' stroke-width='1'/><circle cx='130' cy='50' r='4' fill='none' stroke='#e6edf3' stroke-width='1.5'/><circle cx='270' cy='50' r='4' fill='none' stroke='#e6edf3' stroke-width='1.5'/><text x='130' y='75' text-anchor='middle' fill='#e6edf3' font-size='11'>x = -2</text><text x='270' y='75' text-anchor='middle' fill='#e6edf3' font-size='11'>x = 2</text><text x='80' y='30' fill='#4ade80' font-size='12'>+</text><text x='200' y='30' fill='#f87171' font-size='12'>−</text><text x='320' y='30' fill='#4ade80' font-size='12'>+</text><text x='200' y='95' fill='#e6edf3' font-size='12'>(x-2)(x+2): use + regions</text></svg>"
    },
    {
        "title": "The Sign Diagram: Testing Intervals",
        "body": "<h3>Step-by-Step Sign Analysis</h3><p>After finding roots, test one point in each interval to determine the sign of the expression.</p><p><strong>Process:</strong></p><ol><li>Mark the roots on a number line</li><li>Choose a test point in each region (avoid the roots)</li><li>Plug the test point into the factored form</li><li>Record + (positive) or − (negative) above each region</li><li>Select regions matching your inequality (> 0 means select + regions; < 0 means select − regions)</li></ol><div class='example-box'><h4>Section 2 Example: Complete Sign Diagram</h4><p>Solve \\(x^2 - 5x + 6 < 0\\)</p><p><strong>Factor:</strong> \\((x - 2)(x - 3) < 0\\)</p><p><strong>Roots:</strong> x = 2, x = 3</p><p><strong>Test x = 0 (left region):</strong> (0-2)(0-3) = (-2)(-3) = 6 → POSITIVE</p><p><strong>Test x = 2.5 (middle region):</strong> (2.5-2)(2.5-3) = (0.5)(-0.5) = -0.25 → NEGATIVE ✓</p><p><strong>Test x = 4 (right region):</strong> (4-2)(4-3) = (2)(1) = 2 → POSITIVE</p><p><strong>Solution:</strong> We want < 0, so select the NEGATIVE region: \\(x \\in (2, 3)\\)</p></div>"
    },
    {
        "title": "Repeated Roots and Perfect Squares",
        "body": "<h3>What Happens When a Root Appears Twice?</h3><p>Some quadratics have repeated roots, like \\((x - 3)^2\\). The sign doesn't change at a repeated root.</p><p><strong>Key rule:</strong> Even number of factors with the same root → sign does NOT flip</p><p>Odd number of factors → sign DOES flip</p><div class='example-box'><h4>Section 3 Example: Repeated Root</h4><p>Solve \\((x - 3)^2 > 0\\)</p><p>Root: x = 3 (with multiplicity 2, i.e., appearing twice)</p><p>Test x = 0: (0-3)^2 = 9 → POSITIVE</p><p>Test x = 4: (4-3)^2 = 1 → POSITIVE</p><p>The expression is positive on BOTH sides of x = 3</p><p><strong>Solution:</strong> \\(x \\neq 3\\) or in interval: \\((-\\infty, 3) \\cup (3, \\infty)\\)</p><p>Note: x = 3 itself is excluded because (3-3)^2 = 0, which is NOT > 0</p></div>"
    },
    {
        "title": "Cubic and Higher Degree Inequalities",
        "body": "<h3>Extending to Three or More Factors</h3><p>The sign diagram method works for ANY polynomial. With more factors, you have more regions to test.</p><div class='example-box'><h4>Section 4 Example: Cubic Inequality</h4><p>Solve \\((x - 1)(x - 2)(x - 3) > 0\\)</p><p><strong>Roots:</strong> x = 1, 2, 3 (all with multiplicity 1, so sign flips at each)</p><p><strong>Test x = 0:</strong> (-1)(-2)(-3) = -8 → NEGATIVE</p><p><strong>Test x = 1.5:</strong> (0.5)(-0.5)(-1.5) = 0.375 → POSITIVE ✓</p><p><strong>Test x = 2.5:</strong> (1.5)(0.5)(-0.5) = -0.375 → NEGATIVE</p><p><strong>Test x = 4:</strong> (3)(2)(1) = 6 → POSITIVE ✓</p><p><strong>Solution:</strong> \\(x \\in (1, 2) \\cup (3, \\infty)\\)</p><p>The sign alternates at each odd-multiplicity root: −, +, −, +</p></div>"
    }
]
