TITLE = "Measures of Central Tendency"

SECTIONS = [
    {
        "title": "Mean, Median, Mode: Finding the 'Typical' Value",
        "body": "<div class='concept-box'><p>When you have data, you often want ONE number that represents the whole set—a 'typical' value. We have three main measures, each useful for different situations.</p><p><strong>The three measures of central tendency:</strong></p><ul><li><strong>Mean:</strong> The arithmetic average</li><li><strong>Median:</strong> The middle value when ordered</li><li><strong>Mode:</strong> The most common value</li></ul></div><h3>Quick Example</h3><div class='example-box'><p><strong>Data: 2, 3, 4, 5, 6</strong></p><p>Mean: \((2+3+4+5+6) \div 5 = 4\)</p><p>Median: 4 (middle value when ordered)</p><p>Mode: No mode (all appear once)</p><p>Notice all three are different! Each tells a different story.</p></div>"
    },
    {
        "title": "The Mean (Average)",
        "body": "<h3>Formula for Mean</h3><p>\\(\\bar{x} = \\frac{\\sum x}{n}\\)</p><p><strong>In words:</strong> Add all values, divide by how many values there are.</p><h3>Example 1: Simple Mean</h3><div class='example-box'><p><strong>Test scores: 75, 82, 88, 79, 91</strong></p><p>Sum: \(75 + 82 + 88 + 79 + 91 = 415\)</p><p>Count: 5 values</p><p>Mean = \(415 \div 5 = 83\)</p></div><h3>Example 2: Mean from a Frequency Table</h3><div class='example-box'><p><strong>Number of cars in households:</strong></p><table border='1' style='border-collapse:collapse; margin: 10px 0;'><tr><th style='padding:5px;'>Number</th><th style='padding:5px;'>Frequency</th><th style='padding:5px;'>Number × Freq</th></tr><tr><td style='padding:5px;'>0</td><td style='padding:5px;'>3</td><td style='padding:5px;'>0 × 3 = 0</td></tr><tr><td style='padding:5px;'>1</td><td style='padding:5px;'>7</td><td style='padding:5px;'>1 × 7 = 7</td></tr><tr><td style='padding:5px;'>2</td><td style='padding:5px;'>5</td><td style='padding:5px;'>2 × 5 = 10</td></tr><tr><td style='padding:5px;'>3</td><td style='padding:5px;'>2</td><td style='padding:5px;'>3 × 2 = 6</td></tr></table><p>Sum of (Number × Freq) = \(0 + 7 + 10 + 6 = 23\)</p><p>Total frequency = \(3 + 7 + 5 + 2 = 17\)</p><p>Mean = \(23 \div 17 \approx 1.35\) cars</p></div><h3>Properties of the Mean</h3><ul><li>Uses <strong>ALL</strong> data values</li><li>Can be affected by extreme values (outliers)</li><li>Represents the 'balance point' of data</li><li>Can be a decimal even if all data are whole numbers</li></ul><h3>The Outlier Problem</h3><div class='example-box'><p><strong>Situation 1:</strong> Pocket money: £5, £6, £7, £8, £9</p><p>Mean = £7 ✓ (makes sense)</p><p><strong>Situation 2:</strong> Pocket money: £5, £6, £7, £8, £100</p><p>Mean = \((5+6+7+8+100) \div 5 =\) £25.20</p><p>Only one person got that much! The mean is pulled way up by the outlier.</p></div><div class='success-box'><p><strong>When to use mean:</strong> When data is roughly evenly distributed with no extreme outliers.</p></div>"
    },
    {
        "title": "The Median (Middle Value)",
        "body": "<h3>Finding the Median</h3><p><strong>Step 1:</strong> Arrange data in order (smallest to largest)</p><p><strong>Step 2:</strong> Find the middle value</p><h3>Example 1: Odd Number of Values</h3><div class='example-box'><p><strong>Test scores: 75, 82, 88, 79, 91</strong></p><p>Arrange in order: 75, 79, 82, 88, 91</p><p>↑ (position 3)</p><p><strong>Median = 82</strong></p></div><h3>Example 2: Even Number of Values</h3><div class='example-box'><p><strong>Test scores: 75, 82, 88, 79, 91, 85</strong></p><p>Arrange in order: 75, 79, 82, 85, 88, 91</p><p>Two middle values: 82 and 85</p><p>Median = \((82 + 85) \div 2 = 83.5\)</p></div><h3>Median is Resistant to Outliers</h3><div class='example-box'><p><strong>Data:</strong> £5, £6, £7, £8, £9</p><p>Median = £7</p><p><strong>Data with outlier:</strong> £5, £6, £7, £8, £100</p><p>Arranged: £5, £6, £7, £8, £100</p><p>Median = £7 (still the same!)</p><p>The median was unaffected by the extreme £100 value.</p></div><h3>Properties of the Median</h3><ul><li>Not affected by extreme values (outliers)</li><li>Exactly half the data is above, half below</li><li>Easy to understand—'the middle'</li><li>Good for skewed (unbalanced) data</li></ul><div class='success-box'><p><strong>When to use median:</strong> When there are outliers or skewed data (e.g., house prices, salaries).</p></div>"
    },
    {
        "title": "The Mode (Most Frequent Value)",
        "body": "<h3>Definition</h3><p>The <strong>mode</strong> is the value that appears most frequently.</p><h3>Example 1: Finding the Mode</h3><div class='example-box'><p><strong>Shoe sizes: 4, 5, 5, 5, 6, 6, 7, 8, 8, 9</strong></p><table border='1' style='border-collapse:collapse; margin: 10px 0;'><tr><th style='padding:5px;'>Size</th><th style='padding:5px;'>Frequency</th></tr><tr><td style='padding:5px;'>4</td><td style='padding:5px;'>1</td></tr><tr><td style='padding:5px;'>5</td><td style='padding:5px;'>3 ← highest</td></tr><tr><td style='padding:5px;'>6</td><td style='padding:5px;'>2</td></tr><tr><td style='padding:5px;'>7</td><td style='padding:5px;'>1</td></tr><tr><td style='padding:5px;'>8</td><td style='padding:5px;'>2</td></tr><tr><td style='padding:5px;'>9</td><td style='padding:5px;'>1</td></tr></table><p><strong>Mode = 5</strong> (appears 3 times)</p></div><h3>Special Cases</h3><div class='example-box'><p><strong>No Mode:</strong> 2, 3, 4, 5, 6 (all appear once, so no mode)</p><p><strong>Bimodal:</strong> 3, 3, 3, 5, 5, 5, 7, 8, 9 (both 3 and 5 appear 3 times)</p><p><strong>Multimodal:</strong> Three or more values with equal highest frequency</p></div><h3>Mode for Categorical Data</h3><div class='example-box'><p><strong>Favorite colors:</strong> Red, Blue, Red, Green, Blue, Red, Yellow, Blue, Red</p><p>Red appears 4 times ← most frequent</p><p>Blue appears 3 times</p><p><strong>Mode = Red</strong></p><p>You can't find mean or median for colors, but you CAN find the mode!</p></div><h3>Properties of the Mode</h3><ul><li>Only measure that works for categorical (non-numeric) data</li><li>Easy to find and understand</li><li>Can be unaffected by outliers</li><li>Must be an actual value from the data</li><li>Not useful if no value appears more than once</li></ul><div class='success-box'><p><strong>When to use mode:</strong> For categorical data, or when you want the most common value (e.g., most popular shoe size to stock).</p></div>"
    }
]
