TITLE = "Mode and Range"

SECTIONS = [
    {
        "title": "What is Mode?",
        "body": '<h3>Mode is the Most Frequent Value</h3><p>The <strong>mode</strong> is the value that appears most often in a set of data.</p><div class="concept-box"><strong>Mode = The number that appears most frequently</strong></div><h3>Finding the Mode</h3><p>Simply count how many times each number appears. The number with the highest count is the mode.</p><h3>Example 1: Shoe Sizes</h3><div class="worked-example"><p><strong>Shoe sizes in a class: 4, 5, 5, 5, 6, 6, 7, 8</strong></p><ul><li>Size 4 appears 1 time</li><li>Size 5 appears 3 times</li><li>Size 6 appears 2 times</li><li>Size 7 appears 1 time</li><li>Size 8 appears 1 time</li></ul><p><strong>Mode = 5 (appears most often)</strong></p></div><h3>Example 2: Test Scores</h3><div class="worked-example"><p><strong>Scores: 70, 75, 75, 80, 85, 85, 85, 90</strong></p><ul><li>70 appears 1 time</li><li>75 appears 2 times</li><li>80 appears 1 time</li><li>85 appears 3 times</li><li>90 appears 1 time</li></ul><p><strong>Mode = 85</strong></p></div>'
    },
    {
        "title": "Special Cases: No Mode and Multiple Modes",
        "body": '<h3>No Mode</h3><p>If all numbers appear the same number of times, there is no mode.</p><div class="worked-example"><p><strong>Example: 1, 2, 3, 4, 5</strong></p><p>Each number appears exactly once, so there is no mode.</p></div><h3>Multiple Modes (Bimodal or Multimodal)</h3><p>If two or more numbers appear equally often and more than once, they are all modes.</p><div class="worked-example"><p><strong>Example: 1, 1, 2, 2, 3, 4</strong></p><ul><li>1 appears 2 times</li><li>2 appears 2 times</li><li>3 appears 1 time</li><li>4 appears 1 time</li></ul><p><strong>Modes = 1 and 2 (both appear twice)</strong></p></div>'
    },
    {
        "title": "What is Range?",
        "body": '<h3>Range Shows How Spread Out Data Is</h3><p>The <strong>range</strong> is the difference between the largest and smallest values in a set of data. It shows how spread out the numbers are.</p><div class="concept-box"><strong>Range = Largest value \(-\) Smallest value</strong></div><h3>Example 1: Test Scores</h3><div class="worked-example"><p><strong>Scores: 65, 70, 75, 80, 85, 90, 95</strong></p><ul><li>Largest value = 95</li><li>Smallest value = 65</li><li><strong>Range = \(95 - 65 = 30\)</strong></li></ul></div><h3>Example 2: Daily Temperatures</h3><div class="worked-example"><p><strong>Temperatures: 18°C, 19°C, 21°C, 22°C, 24°C</strong></p><ul><li>Largest = 24°C</li><li>Smallest = 18°C</li><li><strong>Range = \(24 - 18 = 6\)°C</strong></li></ul><p>The range of 6°C shows the variation in temperature.</p></div>'
    },
    {
        "title": "Using Mode in Real Life",
        "body": '<h3>When is Mode Useful?</h3><p>Mode is useful when you want to know the most popular or most common value.</p><h3>Real-World Examples</h3><ul><li><strong>Clothes Sizes:</strong> A shop wants to stock the size that sells most. Mode tells them this. If size M is the mode, they should stock more size M shirts.</li><li><strong>Favorite Colors:</strong> A school is painting a classroom. If blue is the mode favorite color, they paint it blue.</li><li><strong>Popular Games:</strong> A teacher wants to know which game is most popular at recess. Mode shows which game is played most often.</li><li><strong>Homework Time:</strong> In a survey of how long homework takes, the mode shows what is typical for most students.</li></ul>'
    },
    {
        "title": "Comparing Mean, Median, Mode, and Range",
        "body": '<h3>Quick Comparison</h3><table style="width:100%; border-collapse:collapse;"><tr style="background-color: rgba(255,255,255,0.03);"><th style="padding: 8px;"><strong>Average Type</strong></th><th style="padding: 8px;"><strong>What It Shows</strong></th><th style="padding: 8px;"><strong>Use It When</strong></th></tr><tr><td style="padding: 8px;"><strong>Mean</strong></td><td style="padding: 8px;">Sum divided by count</td><td style="padding: 8px;">You want the typical value overall</td></tr><tr style="background-color: rgba(255,255,255,0.03);"><td style="padding: 8px;"><strong>Median</strong></td><td style="padding: 8px;">The middle value</td><td style="padding: 8px;">There are extreme values</td></tr><tr><td style="padding: 8px;"><strong>Mode</strong></td><td style="padding: 8px;">The most frequent value</td><td style="padding: 8px;">You want the most popular value</td></tr><tr style="background-color: rgba(255,255,255,0.03);"><td style="padding: 8px;"><strong>Range</strong></td><td style="padding: 8px;">How spread out the data is</td><td style="padding: 8px;">You want to see variation</td></tr></table><h3>Example: Compare All Four</h3><div class="worked-example"><p><strong>Test scores: 60, 70, 70, 75, 80, 85, 95</strong></p><ul><li><strong>Mean:</strong> \((60 + 70 + 70 + 75 + 80 + 85 + 95) \div 7 = 535 \div 7 \\approx 76.4\)</li><li><strong>Median:</strong> 70, 70, 75, 80, 85, 95 → middle = 75</li><li><strong>Mode:</strong> 70 (appears twice)</li><li><strong>Range:</strong> \(95 - 60 = 35\)</li></ul><p>Each statistic tells us something different!</p></div>'
    }
]
