TITLE = "What is Perimeter?"

SECTIONS = [
    {
        "title": "Perimeter: Distance Around a Shape",
        "body": "<h3>The Fence Analogy</h3><p>Imagine you want to build a <strong>fence around your garden</strong>. How much fencing do you need? That's PERIMETER—the distance AROUND a shape.</p><div class='concept-box'><p><strong>Perimeter</strong> = the total distance around the edge of a shape.</p><p>It's <strong>1-dimensional</strong> (measured in metres, centimetres, kilometres, etc.)</p></div><svg viewBox='0 0 360 200' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0; max-width: 360px; width: 100%;'><rect x='50' y='30' width='200' height='120' fill='none' stroke='#2ecc71' stroke-width='3'/><line x1='50' y1='30' x2='250' y2='30' stroke='#e74c3c' stroke-width='2' stroke-dasharray='5,5'/><line x1='250' y1='30' x2='250' y2='150' stroke='#e74c3c' stroke-width='2' stroke-dasharray='5,5'/><line x1='250' y1='150' x2='50' y2='150' stroke='#e74c3c' stroke-width='2' stroke-dasharray='5,5'/><line x1='50' y1='150' x2='50' y2='30' stroke='#e74c3c' stroke-width='2' stroke-dasharray='5,5'/><text x='150' y='15' font-size='12' fill='currentColor' text-anchor='middle'>200 cm (length)</text><text x='265' y='95' font-size='12' fill='currentColor' text-anchor='start'>120 cm</text><text x='265' y='110' font-size='12' fill='currentColor' text-anchor='start'>(width)</text><text x='150' y='185' font-size='11' fill='#e74c3c' font-weight='bold' text-anchor='middle'>Perimeter path (dotted red)</text></svg>"
    },
    {
        "title": "Counting Sides to Find Perimeter",
        "body": "<h3>The Basic Method: Add All the Sides</h3><p>To find the perimeter of ANY shape, just <strong>add up all the side lengths</strong>.</p><div class='worked-example'><h4>Example: A Triangle with sides 3 m, 4 m, and 5 m</h4><p>Perimeter = \\(3 + 4 + 5 = \\)<strong>12 metres</strong></p></div><svg width='320' height='250' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0;'><polygon points='160,40 80,200 240,200' fill='#ecf0f1' stroke='#2980b9' stroke-width='3'/><text x='85' y='120' font-size='14' font-weight='bold' fill='#2980b9' text-anchor='end'>3 m</text><text x='235' y='120' font-size='14' font-weight='bold' fill='#2980b9' text-anchor='start'>4 m</text><text x='160' y='225' font-size='14' font-weight='bold' fill='#2980b9' text-anchor='middle'>5 m</text><circle cx='160' cy='40' r='5' fill='#e74c3c'/><circle cx='80' cy='200' r='5' fill='#e74c3c'/><circle cx='240' cy='200' r='5' fill='#e74c3c'/></svg><div class='success-box'><p><strong>Remember:</strong> Perimeter always measures distance, so the answer is in linear units (m, cm, km)—NOT square units.</p></div>"
    },
    {
        "title": "More Shapes: Pentagon & Irregular Polygons",
        "body": "<h3>Any Polygon Works the Same Way</h3><p>Whether it's a triangle, square, pentagon, or any other polygon, the method is the same:</p><div class='worked-example'><h4>Example: A Pentagon with sides 2 m, 2 m, 3 m, 2 m, 3 m</h4><p>Perimeter = \\(2 + 2 + 3 + 2 + 3 = \\)<strong>14 metres</strong></p></div><svg width='300' height='280' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0;'><polygon points='150,20 220,90 190,180 110,180 80,90' fill='#f3f4f6' stroke='#9b59b6' stroke-width='3'/><text x='190' y='45' font-size='12' font-weight='bold' fill='#9b59b6'>2m</text><text x='225' y='130' font-size='12' font-weight='bold' fill='#9b59b6'>3m</text><text x='150' y='195' font-size='12' font-weight='bold' fill='#9b59b6'>2m</text><text x='70' y='130' font-size='12' font-weight='bold' fill='#9b59b6'>3m</text><text x='100' y='60' font-size='12' font-weight='bold' fill='#9b59b6'>2m</text></svg><div class='warning-box'><p><strong>Watch out:</strong> The sides of a shape don't have to be equal. Just add them all up!</p></div>"
    },
    {
        "title": "Real-World Perimeter",
        "body": "<h3>When Do We Use Perimeter?</h3><ul><li><strong>Building a fence:</strong> How many metres of fencing do you need?</li><li><strong>Painting a border:</strong> How much trim paint for the edge of a room?</li><li><strong>Running around a track:</strong> How far did you run?</li><li><strong>Framing a picture:</strong> How much frame material?</li></ul><div class='concept-box'><p><strong>Key idea:</strong> Perimeter is always about the <strong>distance AROUND</strong> a shape, like walking around the edge of a park.</p></div><h3>Challenge Question</h3><div class='worked-example'><p>A farmer has a rectangular paddock: 40 metres long and 30 metres wide. She wants to build a fence around it. How many metres of fencing does she need?</p><p>Perimeter = \\(40 + 30 + 40 + 30 = \\)<strong>140 metres</strong> of fencing.</p></div>"
    }
]
