TITLE = "What is Perimeter?"

SECTIONS = [
    {
        "title": "Perimeter: Distance Around a Shape",
        "body": "<h3>The Fence Analogy</h3><p>Imagine you want to build a <strong>fence around your garden</strong>. How much fencing do you need? That's PERIMETER—the distance AROUND a shape.</p><div class='concept-box'><p><strong>Perimeter</strong> = the total distance around the edge of a shape.</p><p>It's <strong>1-dimensional</strong> (measured in metres, centimetres, kilometres, etc.)</p></div><svg viewBox='0 0 380 215' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0; max-width: 380px; width: 100%;'><rect x='60' y='35' width='200' height='120' fill='none' stroke='#2ecc71' stroke-width='3' rx='4'/><line x1='60' y1='35' x2='260' y2='35' stroke='#e74c3c' stroke-width='2' stroke-dasharray='5,5'/><line x1='260' y1='35' x2='260' y2='155' stroke='#e74c3c' stroke-width='2' stroke-dasharray='5,5'/><line x1='260' y1='155' x2='60' y2='155' stroke='#e74c3c' stroke-width='2' stroke-dasharray='5,5'/><line x1='60' y1='155' x2='60' y2='35' stroke='#e74c3c' stroke-width='2' stroke-dasharray='5,5'/><text x='160' y='22' font-family='sans-serif' font-size='13' fill='currentColor' text-anchor='middle'>200 cm (length)</text><text x='275' y='92' font-family='sans-serif' font-size='13' fill='currentColor' text-anchor='start'>120 cm</text><text x='275' y='108' font-family='sans-serif' font-size='13' fill='currentColor' text-anchor='start'>(width)</text><text x='160' y='200' font-family='sans-serif' font-size='12' fill='currentColor' font-weight='bold' text-anchor='middle'>Perimeter path (dotted red)</text></svg>"
    },
    {
        "title": "Counting Sides to Find Perimeter",
        "body": "<h3>The Basic Method: Add All the Sides</h3><p>To find the perimeter of ANY shape, just <strong>add up all the side lengths</strong>.</p><div class='worked-example'><h4>Example: A Triangle with sides 3 m, 4 m, and 5 m</h4><p>Perimeter = \\(3 + 4 + 5 = \\)<strong>12 metres</strong></p></div><svg viewBox='0 0 330 250' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0; max-width: 330px; width: 100%;'><polygon points='165,40 75,200 255,200' fill='#ecf0f1' stroke='#2980b9' stroke-width='3'/><text x='90' y='118' font-family='sans-serif' font-size='14' font-weight='bold' fill='currentColor' text-anchor='end'>3 m</text><text x='240' y='118' font-family='sans-serif' font-size='14' font-weight='bold' fill='currentColor' text-anchor='start'>4 m</text><text x='165' y='232' font-family='sans-serif' font-size='14' font-weight='bold' fill='currentColor' text-anchor='middle'>5 m</text><circle cx='165' cy='40' r='5' fill='#e74c3c'/><circle cx='75' cy='200' r='5' fill='#e74c3c'/><circle cx='255' cy='200' r='5' fill='#e74c3c'/></svg><div class='success-box'><p><strong>Remember:</strong> Perimeter always measures distance, so the answer is in linear units (m, cm, km)—NOT square units.</p></div>"
    },
    {
        "title": "More Shapes: Pentagon & Irregular Polygons",
        "body": "<h3>Any Polygon Works the Same Way</h3><p>Whether it's a triangle, square, pentagon, or any other polygon, the method is the same:</p><div class='worked-example'><h4>Example: A Pentagon with sides 2 m, 2 m, 3 m, 2 m, 3 m</h4><p>Perimeter = \\(2 + 2 + 3 + 2 + 3 = \\)<strong>14 metres</strong></p></div><svg viewBox='0 0 310 215' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0; max-width: 310px; width: 100%;'><polygon points='155,25 225,85 200,175 110,175 85,85' fill='#f3f4f6' stroke='#9b59b6' stroke-width='3'/><text x='200' y='48' font-family='sans-serif' font-size='13' font-weight='bold' fill='currentColor'>2 m</text><text x='228' y='132' font-family='sans-serif' font-size='13' font-weight='bold' fill='currentColor'>3 m</text><text x='155' y='200' font-family='sans-serif' font-size='13' font-weight='bold' fill='currentColor' text-anchor='middle'>2 m</text><text x='62' y='132' font-family='sans-serif' font-size='13' font-weight='bold' fill='currentColor' text-anchor='end'>3 m</text><text x='100' y='48' font-family='sans-serif' font-size='13' font-weight='bold' fill='currentColor' text-anchor='end'>2 m</text></svg><div class='warning-box'><p><strong>Watch out:</strong> The sides of a shape don't have to be equal. Just add them all up!</p></div>"
    },
    {
        "title": "Real-World Perimeter",
        "body": "<h3>When Do We Use Perimeter?</h3><ul><li><strong>Building a fence:</strong> How many metres of fencing do you need?</li><li><strong>Painting a border:</strong> How much trim paint for the edge of a room?</li><li><strong>Running around a track:</strong> How far did you run?</li><li><strong>Framing a picture:</strong> How much frame material?</li></ul><div class='concept-box'><p><strong>Key idea:</strong> Perimeter is always about the <strong>distance AROUND</strong> a shape, like walking around the edge of a park.</p></div><h3>Challenge Question</h3><div class='worked-example'><p>A farmer has a rectangular paddock: 40 metres long and 30 metres wide. She wants to build a fence around it. How many metres of fencing does she need?</p><p>Perimeter = \\(40 + 30 + 40 + 30 = \\)<strong>140 metres</strong> of fencing.</p></div>"
    }
]
