# Concept 2: Parameters and Arguments

TITLE = "Parameters and Arguments"

SECTIONS = [
    {
        "id": "py_functions_02_01",
        "title": "Parameters vs. Arguments",
        "body": '<div class="concept-box"><h4>The Key Distinction</h4><ul><li><strong>Parameter:</strong> A variable in the function definition</li><li><strong>Argument:</strong> The actual value passed when calling the function</li></ul></div><div class="worked-example"><h4>Parameters vs. Arguments Example</h4><pre># Parameters are in the definition\ndef add(a, b):  # a and b are parameters\n    return a + b\n\n# Arguments are the values we pass\nresult = add(3, 5)  # 3 and 5 are arguments\nprint(result)  # Output: 8</pre></div><h4>Understanding the Flow</h4><ol><li>Define the function with parameter names</li><li>Call the function with actual argument values</li><li>Inside the function, parameters take on the values of arguments</li><li>Function logic uses the parameter values</li></ol>'
    },
    {
        "id": "py_functions_02_02",
        "title": "Positional and Keyword Arguments",
        "body": '<h3>Positional Arguments</h3><p>Arguments are matched to parameters based on their position in the function call.</p><div class="worked-example"><h4>Positional Arguments</h4><pre>def introduce(name, age, city):\n    print(f"{name} is {age} years old and lives in {city}")\n\n# Positional: matched by order\nintroduce("Alice", 30, "New York")\n# Output: Alice is 30 years old and lives in New York\n\n# Wrong order = wrong results\nintroduce(30, "Alice", "New York")\n# Output: 30 is Alice years old and lives in New York</pre></div><h3>Keyword Arguments</h3><p>You can specify which parameter gets which value using parameter names.</p><div class="worked-example"><h4>Keyword Arguments</h4><pre>def introduce(name, age, city):\n    print(f"{name} is {age} years old and lives in {city}")\n\n# Keyword arguments: order does not matter\nintroduce(city="Boston", name="Bob", age=25)\n# Output: Bob is 25 years old and lives in Boston\n\n# Mix positional and keyword (positional must come first)\nintroduce("Carol", age=28, city="Chicago")\n# Output: Carol is 28 years old and lives in Chicago</pre></div><div class="warning-box"><h4>Positional Arguments Must Come First</h4><p>If you use both positional and keyword arguments, all positional arguments must come before keyword arguments.</p></div>'
    },
    {
        "id": "py_functions_02_03",
        "title": "Default Parameters and Variable Arguments",
        "body": '<h3>Default Parameters</h3><p>You can specify default values for parameters. If an argument is not provided, the default is used.</p><div class="worked-example"><h4>Default Parameter Values</h4><pre>def greet(name, greeting="Hello"):\n    print(f"{greeting}, {name}!")\n\ngreet("Alice")  # Uses default greeting\n# Output: Hello, Alice!\n\ngreet("Bob", "Hi")  # Overrides default\n# Output: Hi, Bob!\n\ngreet("Carol", greeting="Hey")  # Keyword with default override\n# Output: Hey, Carol!</pre></div><div class="success-box"><h4>Best Practice: Defaults for Common Cases</h4><p>Use default parameters for values that are often the same, making the function easier to use.</p></div><h3>Variable-Length Arguments: *args</h3><p>The <code>*args</code> syntax allows a function to accept any number of positional arguments.</p><div class="worked-example"><h4>Using *args</h4><pre>def sum_all(*numbers):\n    total = 0\n    for num in numbers:\n        total += num\n    return total\n\nprint(sum_all(1, 2, 3))  # Output: 6\nprint(sum_all(1, 2, 3, 4, 5))  # Output: 15\nprint(sum_all())  # Output: 0</pre></div><h3>Variable Keyword Arguments: **kwargs</h3><p>The <code>**kwargs</code> syntax allows a function to accept any number of keyword arguments.</p><div class="worked-example"><h4>Using **kwargs</h4><pre>def print_info(**info):\n    for key, value in info.items():\n        print(f"{key}: {value}")\n\nprint_info(name="Alice", age=30, city="NYC")\n# Output:\n# name: Alice\n# age: 30\n# city: NYC</pre></div>'
    },
    {
        "id": "py_functions_02_04",
        "title": "Advanced Parameter Patterns",
        "body": '<h3>Combining Positional, *args, and **kwargs</h3><p>You can combine all three types in a single function. The order matters: positional, then *args, then **kwargs.</p><div class="worked-example"><h4>Complete Function Signature</h4><pre>def flexible_function(name, age, *hobbies, **details):\n    print(f"Name: {name}")\n    print(f"Age: {age}")\n    print(f"Hobbies: {hobbies}")\n    print(f"Details: {details}")\n\nflexible_function(\n    "Alice", 30,\n    "reading", "hiking", "coding",\n    city="NYC", job="Engineer"\n)\n# Output:\n# Name: Alice\n# Age: 30\n# Hobbies: ("reading", "hiking", "coding")\n# Details: {"city": "NYC", "job": "Engineer"}</pre></div><h3>Type Hints for Clarity</h3><p>Python allows you to specify parameter types using type hints. This improves code clarity and helps catch errors.</p><div class="worked-example"><h4>Type Hints Example</h4><pre>def add(a: int, b: int) -> int:\n    """Add two integers and return the sum."""\n    return a + b\n\ndef greet(name: str) -> None:\n    """Greet someone by name."""\n    print(f"Hello, {name}!")\n\n# Type hints do not enforce types, but document intent\nresult = add(3, 5)  # Correct usage\nresult = add("3", "5")  # Still works, but not recommended</pre></div><div class="concept-box"><h4>Benefits of Type Hints</h4><ul><li>Self-documenting code</li><li>IDE autocomplete improvements</li><li>Tools can catch potential bugs</li><li>Easier collaboration on larger projects</li></ul></div>'
    }
]
