# Concept 1: Defining Functions

TITLE = "Defining Functions"

SECTIONS = [
    {
        "id": "py_functions_01_01",
        "title": "What is a Function?",
        "body": '<div class="concept-box"><h3>Core Principle</h3><p>A function is a reusable block of code that performs a specific task. Functions are fundamental to programming because they allow us to organize code, avoid repetition, and make our programs more readable and maintainable.</p></div><h4>Key Concepts</h4><ul><li><strong>Definition:</strong> Creating a function using the <code>def</code> keyword</li><li><strong>Name:</strong> Functions must have meaningful names that describe their purpose</li><li><strong>Body:</strong> The indented block of code that executes when the function is called</li><li><strong>Invocation:</strong> Calling a function to execute its code</li></ul><div class="worked-example"><h4>Example: A Simple Function</h4><pre>def greet():\n    print("Hello, World!")\n\ngreet()  # Call the function\n# Output: Hello, World!</pre></div><h4>Anatomy of a Function</h4><p>Every function has several parts:</p><ol><li><strong>def keyword:</strong> Tells Python we are defining a function</li><li><strong>Function name:</strong> A descriptive identifier (snake_case)</li><li><strong>Parentheses:</strong> Contain parameters (if any)</li><li><strong>Colon:</strong> Marks the start of the function body</li><li><strong>Indented block:</strong> Contains the function code</li></ol>'
    },
    {
        "id": "py_functions_01_02",
        "title": "Function Naming and Best Practices",
        "body": '<h3>Naming Conventions</h3><p>Good function names are crucial for code readability and maintainability.</p><div class="concept-box"><h4>Python Naming Standards (PEP 8)</h4><ul><li>Use <strong>snake_case</strong>: lowercase with underscores between words</li><li>Choose <strong>descriptive names</strong> that explain what the function does</li><li>Use <strong>verb-based names</strong> when appropriate: <code>calculate_area()</code>, <code>validate_input()</code></li><li>Avoid single-letter names except for simple iterators</li></ul></div><div class="worked-example"><h4>Good vs. Poor Function Names</h4><pre># Good names (describe what the function does)\ndef calculate_sum(numbers):\n    return sum(numbers)\n\ndef is_valid_email(email):\n    return "@" in email\n\ndef fetch_user_data(user_id):\n    pass\n\n# Poor names (unclear or too vague)\ndef do_stuff():\n    pass\n\ndef x(y):\n    return y * 2</pre></div><h3>Documentation</h3><p>Every function should have a docstring explaining its purpose, parameters, and return value.</p><div class="success-box"><h4>Well-Documented Function</h4><pre>def calculate_circle_area(radius):\n    """\n    Calculate the area of a circle.\n\n    Args:\n        radius (float): The radius of the circle\n\n    Returns:\n        float: The area of the circle\n    """\n    import math\n    return math.pi * radius ** 2</pre></div>'
    },
    {
        "id": "py_functions_01_03",
        "title": "Function Structure and Execution Flow",
        "body": '<h3>How Functions Execute</h3><div class="concept-box"><h4>Execution Order</h4><p>When Python encounters a function definition, it <strong>does not</strong> execute the code inside. Instead, it stores the function definition. The code only executes when you <strong>call</strong> the function.</p></div><div class="worked-example"><h4>Example: Definition vs. Invocation</h4><pre># Step 1: Define the function (code does not run yet)\ndef say_hello():\n    print("Hello!")\n\n# Step 2: Call the function (now the code runs)\nsay_hello()  # Output: Hello!\nsay_hello()  # Call again, output: Hello!</pre></div><h3>Function Scope and Lifetime</h3><p>Functions create their own scope. Variables defined inside a function only exist while the function is executing.</p><div class="warning-box"><h4>Important: Variables Inside Functions</h4><p>Variables created inside a function are <strong>local</strong> to that function. They are created when the function is called and destroyed when the function exits.</p></div><h3>Empty Functions and Placeholders</h3><p>Sometimes you need to define a function but do not want to add code yet. Use the <code>pass</code> statement.</p><div class="worked-example"><h4>Using pass</h4><pre>def function_to_implement_later():\n    pass  # Placeholder; code goes here later\n\ndef another_function():\n    # This will cause an IndentationError without pass\n    pass</pre></div>'
    },
    {
        "id": "py_functions_01_04",
        "title": "First-Principles Deep Dive",
        "body": '<h3>Why Functions Matter: First Principles</h3><div class="concept-box"><h4>Core Programming Principle: DRY (Do not Repeat Yourself)</h4><p>Functions allow you to write code once and reuse it many times. This reduces errors, makes updates easier, and improves code clarity.</p></div><h4>The Cost of Repetition</h4><p>Without functions, you might write the same logic multiple times. This creates several problems:</p><ul><li>When you find a bug, you must fix it in every copy</li><li>Code becomes longer and harder to understand</li><li>Changes become more error-prone</li><li>Testing becomes more complex</li></ul><div class="worked-example"><h4>Without Functions (Repetitive)</h4><pre># Calculate area without functions\nradius1 = 5\narea1 = 3.14159 * radius1 * radius1\nprint(f"Circle 1 area: {area1}")\n\nradius2 = 7\narea2 = 3.14159 * radius2 * radius2\nprint(f"Circle 2 area: {area2}")\n\nradius3 = 3\narea3 = 3.14159 * radius3 * radius3\nprint(f"Circle 3 area: {area3}")</pre></div><div class="success-box"><h4>With Functions (DRY)</h4><pre>import math\n\ndef calculate_circle_area(radius):\n    return math.pi * radius * radius\n\n# Now reuse the same function\nfor radius in [5, 7, 3]:\n    area = calculate_circle_area(radius)\n    print(f"Circle area: {area}")</pre></div><h3>Functions as Abstractions</h3><p>Functions let you hide complexity behind a simple interface. You use the function without needing to understand every detail of how it works internally.</p>'
    }
]
