TITLE = "Perimeter vs Area: Key Differences"

SECTIONS = [
    {
        "title": "The Fundamental Difference",
        "body": "<h3>One Dimension vs Two Dimensions</h3><div class='concept-box'><p><strong>PERIMETER:</strong> Distance AROUND the shape (1D) — measured in linear units (m, cm, km)</p><p><strong>AREA:</strong> Space INSIDE the shape (2D) — measured in SQUARE units (m², cm², km²)</p></div><h3>The Garden Analogy</h3><p>Imagine a garden shaped like a rectangle.</p><ul><li><strong>Perimeter:</strong> How much fencing do you need to go AROUND the garden? (The fence goes around the edge.)</li><li><strong>Area:</strong> How many square metres of land do you have? (The land is the space inside.)</li></ul><svg width='320' height='240' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0;'><g><rect x='50' y='40' width='220' height='140' fill='#d1fae5' stroke='#059669' stroke-width='3' rx='4'/><rect x='60' y='50' width='200' height='120' fill='#a7f3d0' stroke='#10b981' stroke-width='1' stroke-dasharray='3,3' rx='4'/><text x='160' y='120' font-size='13' text-anchor='middle' fill='currentColor'><tspan x='160' dy='0'>This space is</tspan><tspan x='160' dy='16'>the AREA</tspan></text><text x='35' y='115' font-size='11' font-weight='bold' fill='#059669'>FENCE</text><text x='35' y='130' font-size='11' font-weight='bold' fill='#059669'>(Perimeter)</text></g></svg>"
    },
    {
        "title": "Same Perimeter, Different Area",
        "body": "<h3>Rectangles with Same Perimeter</h3><p>Here's a surprising fact: <strong>Shapes with the SAME perimeter can have DIFFERENT areas!</strong></p><div class='worked-example'><h4>Rectangle A: 5 metres × 1 metre</h4><p>Perimeter = \\(2(5 + 1) = 12\\) metres</p><p>Area = \\(5 \\times 1 = 5\\) m²</p></div><div class='worked-example'><h4>Rectangle B: 4 metres × 2 metres</h4><p>Perimeter = \\(2(4 + 2) = 12\\) metres</p><p>Area = \\(4 \\times 2 = 8\\) m²</p></div><svg width='360' height='240' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0;'><g><rect x='30' y='30' width='130' height='26' fill='#fecaca' stroke='#dc2626' stroke-width='2' rx='4'/><text x='95' y='49' font-size='11' text-anchor='middle' fill='currentColor'>A: 5×1</text><rect x='30' y='70' width='104' height='52' fill='#fbbf24' stroke='#d97706' stroke-width='2' rx='4'/><text x='82' y='100' font-size='11' text-anchor='middle' fill='currentColor'>B: 4×2</text><text x='180' y='50' font-size='12' fill='currentColor'><tspan>A: P = 12 m</tspan><tspan x='180' dy='16'>   A = 5 m²</tspan></text><text x='180' y='100' font-size='12' fill='currentColor'><tspan>B: P = 12 m</tspan><tspan x='180' dy='16'>   A = 8 m²</tspan></text><text x='95' y='150' font-size='11' font-style='italic' fill='currentColor' opacity='0.6' text-anchor='middle'>Same perimeter, but</text><text x='95' y='165' font-size='11' font-style='italic' fill='currentColor' opacity='0.6' text-anchor='middle'>different areas!</text></g></svg><div class='success-box'><p><strong>Key insight:</strong> Perimeter and area are INDEPENDENT! One doesn't determine the other.</p></div>"
    },
    {
        "title": "Same Area, Different Perimeter",
        "body": "<h3>Rectangles with Same Area</h3><p>Now here's another surprise: <strong>Shapes with the SAME area can have DIFFERENT perimeters!</strong></p><div class='worked-example'><h4>Rectangle C: 12 metres × 1 metre</h4><p>Perimeter = \\(2(12 + 1) = 26\\) metres</p><p>Area = \\(12 \\times 1 = 12\\) m²</p></div><div class='worked-example'><h4>Rectangle D: 4 metres × 3 metres</h4><p>Perimeter = \\(2(4 + 3) = 14\\) metres</p><p>Area = \\(4 \\times 3 = 12\\) m²</p></div><svg width='360' height='240' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0;'><g><rect x='30' y='30' width='156' height='13' fill='#c7d2fe' stroke='#4f46e5' stroke-width='2' rx='4'/><text x='108' y='42' font-size='10' text-anchor='middle' fill='currentColor'>C: 12×1</text><rect x='30' y='60' width='104' height='52' fill='#a78bfa' stroke='#7c3aed' stroke-width='2' rx='4'/><text x='82' y='90' font-size='11' text-anchor='middle' fill='currentColor'>D: 4×3</text><text x='200' y='50' font-size='12' fill='currentColor'><tspan>C: P = 26 m</tspan><tspan x='200' dy='16'>   A = 12 m²</tspan></text><text x='200' y='100' font-size='12' fill='currentColor'><tspan>D: P = 14 m</tspan><tspan x='200' dy='16'>   A = 12 m²</tspan></text><text x='95' y='150' font-size='11' font-style='italic' fill='currentColor' opacity='0.6' text-anchor='middle'>Same area, but</text><text x='95' y='165' font-size='11' font-style='italic' fill='currentColor' opacity='0.6' text-anchor='middle'>different perimeters!</text></g></svg><div class='success-box'><p><strong>The squarer the shape, the smaller the perimeter for a given area!</strong></p></div>"
    },
    {
        "title": "Real-World Significance",
        "body": "<h3>Why This Matters in Real Life</h3><h4>Fencing vs Seeding</h4><div class='worked-example'><p><strong>Farmer Problem:</strong> You have a 20-metre perimeter to fence. Do you want a long, thin garden (5m × 5m) or a wider one (6m × 4m)?</p><p>Option 1: \\(5 \\times 5\\) square — Area = \\(25\\) m²</p><p>Option 2: \\(6 \\times 4\\) rectangle — Area = \\(24\\) m²</p><p>The square garden gives more space to plant!</p></div><h4>Perimeter Matters For:</h4><ul><li>Fencing a garden</li><li>Building a fence</li><li>Painting a border</li><li>Adding trim to a room</li></ul><h4>Area Matters For:</h4><ul><li>Painting walls</li><li>Laying carpet</li><li>Tiling a floor</li><li>Seeding a lawn</li><li>Covering with mulch</li></ul><div class='warning-box'><p><strong>Common mistake:</strong> Assuming a large perimeter means a large area. They're independent!</p></div>"
    }
]
