TITLE = "Perimeter vs Area: Key Differences"

SECTIONS = [
    {
        "title": "The Fundamental Difference",
        "body": "<h3>One Dimension vs Two Dimensions</h3><div class='concept-box'><p><strong>PERIMETER:</strong> Distance AROUND the shape (1D) — measured in linear units (m, cm, km)</p><p><strong>AREA:</strong> Space INSIDE the shape (2D) — measured in SQUARE units (m², cm², km²)</p></div><h3>The Garden Analogy</h3><p>Imagine a garden shaped like a rectangle.</p><ul><li><strong>Perimeter:</strong> How much fencing do you need to go AROUND the garden? (The fence goes around the edge.)</li><li><strong>Area:</strong> How many square metres of land do you have? (The land is the space inside.)</li></ul><svg viewBox='0 0 340 240' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0; max-width: 340px; width: 100%;'><rect x='70' y='40' width='220' height='140' fill='#d1fae5' stroke='#059669' stroke-width='3' rx='4'/><rect x='80' y='50' width='200' height='120' fill='#a7f3d0' stroke='#10b981' stroke-width='1' stroke-dasharray='3,3' rx='4'/><text x='180' y='108' font-family='sans-serif' font-size='13' text-anchor='middle' fill='currentColor'>This space is</text><text x='180' y='126' font-family='sans-serif' font-size='13' text-anchor='middle' fill='currentColor'>the AREA</text><text x='30' y='108' font-family='sans-serif' font-size='11' font-weight='bold' fill='currentColor'>FENCE</text><text x='30' y='126' font-family='sans-serif' font-size='11' fill='currentColor'>(Perimeter)</text></svg>"
    },
    {
        "title": "Same Perimeter, Different Area",
        "body": "<h3>Rectangles with Same Perimeter</h3><p>Here's a surprising fact: <strong>Shapes with the SAME perimeter can have DIFFERENT areas!</strong></p><div class='worked-example'><h4>Rectangle A: 5 metres × 1 metre</h4><p>Perimeter = \\(2(5 + 1) = 12\\) metres</p><p>Area = \\(5 \\times 1 = 5\\) m²</p></div><div class='worked-example'><h4>Rectangle B: 4 metres × 2 metres</h4><p>Perimeter = \\(2(4 + 2) = 12\\) metres</p><p>Area = \\(4 \\times 2 = 8\\) m²</p></div><svg viewBox='0 0 370 185' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0; max-width: 370px; width: 100%;'><rect x='30' y='20' width='130' height='26' fill='#fecaca' stroke='#dc2626' stroke-width='2' rx='4'/><text x='95' y='39' font-family='sans-serif' font-size='12' text-anchor='middle' fill='currentColor'>A: 5 x 1</text><rect x='30' y='66' width='104' height='52' fill='#fbbf24' stroke='#d97706' stroke-width='2' rx='4'/><text x='82' y='96' font-family='sans-serif' font-size='12' text-anchor='middle' fill='currentColor'>B: 4 x 2</text><text x='195' y='30' font-family='sans-serif' font-size='12' fill='currentColor'>A: P = 12 m</text><text x='195' y='48' font-family='sans-serif' font-size='12' fill='currentColor'>    A = 5 m2</text><text x='195' y='82' font-family='sans-serif' font-size='12' fill='currentColor'>B: P = 12 m</text><text x='195' y='100' font-family='sans-serif' font-size='12' fill='currentColor'>    A = 8 m2</text><text x='185' y='150' font-family='sans-serif' font-size='12' font-style='italic' fill='currentColor' text-anchor='middle'>Same perimeter, different areas!</text></svg><div class='success-box'><p><strong>Key insight:</strong> Perimeter and area are INDEPENDENT! One doesn't determine the other.</p></div>"
    },
    {
        "title": "Same Area, Different Perimeter",
        "body": "<h3>Rectangles with Same Area</h3><p>Now here's another surprise: <strong>Shapes with the SAME area can have DIFFERENT perimeters!</strong></p><div class='worked-example'><h4>Rectangle C: 12 metres × 1 metre</h4><p>Perimeter = \\(2(12 + 1) = 26\\) metres</p><p>Area = \\(12 \\times 1 = 12\\) m²</p></div><div class='worked-example'><h4>Rectangle D: 4 metres × 3 metres</h4><p>Perimeter = \\(2(4 + 3) = 14\\) metres</p><p>Area = \\(4 \\times 3 = 12\\) m²</p></div><svg viewBox='0 0 370 185' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0; max-width: 370px; width: 100%;'><rect x='30' y='20' width='156' height='18' fill='#c7d2fe' stroke='#4f46e5' stroke-width='2' rx='4'/><text x='108' y='35' font-family='sans-serif' font-size='11' text-anchor='middle' fill='currentColor'>C: 12 x 1</text><rect x='30' y='58' width='104' height='52' fill='#a78bfa' stroke='#7c3aed' stroke-width='2' rx='4'/><text x='82' y='88' font-family='sans-serif' font-size='12' text-anchor='middle' fill='currentColor'>D: 4 x 3</text><text x='215' y='30' font-family='sans-serif' font-size='12' fill='currentColor'>C: P = 26 m</text><text x='215' y='48' font-family='sans-serif' font-size='12' fill='currentColor'>    A = 12 m2</text><text x='215' y='78' font-family='sans-serif' font-size='12' fill='currentColor'>D: P = 14 m</text><text x='215' y='96' font-family='sans-serif' font-size='12' fill='currentColor'>    A = 12 m2</text><text x='185' y='150' font-family='sans-serif' font-size='12' font-style='italic' fill='currentColor' text-anchor='middle'>Same area, different perimeters!</text></svg><div class='success-box'><p><strong>The squarer the shape, the smaller the perimeter for a given area!</strong></p></div>"
    },
    {
        "title": "Real-World Significance",
        "body": "<h3>Why This Matters in Real Life</h3><h4>Fencing vs Seeding</h4><div class='worked-example'><p><strong>Farmer Problem:</strong> You have a 20-metre perimeter to fence. Do you want a long, thin garden (5m × 5m) or a wider one (6m × 4m)?</p><p>Option 1: \\(5 \\times 5\\) square — Area = \\(25\\) m²</p><p>Option 2: \\(6 \\times 4\\) rectangle — Area = \\(24\\) m²</p><p>The square garden gives more space to plant!</p></div><h4>Perimeter Matters For:</h4><ul><li>Fencing a garden</li><li>Building a fence</li><li>Painting a border</li><li>Adding trim to a room</li></ul><h4>Area Matters For:</h4><ul><li>Painting walls</li><li>Laying carpet</li><li>Tiling a floor</li><li>Seeding a lawn</li><li>Covering with mulch</li></ul><div class='warning-box'><p><strong>Common mistake:</strong> Assuming a large perimeter means a large area. They're independent!</p></div>"
    }
]
