TITLE = "Perimeter Formulas"

SECTIONS = [
    {
        "title": "Formula for Rectangle Perimeter",
        "body": "<h3>The Rectangle Formula</h3><p>A rectangle has <strong>opposite sides that are equal</strong>. Instead of adding four numbers, we can use a shortcut:</p><div class='concept-box'><p><strong>Perimeter of Rectangle = \\(2 \\times \\text{length} + 2 \\times \\text{width}\\)</strong></p><p>Or: \\(P = 2l + 2w\\)</p><p>Or: \\(P = 2(l + w)\\)</p></div><svg viewBox='0 0 400 220' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0; max-width: 400px; width: 100%;'><rect x='80' y='40' width='220' height='100' fill='#e8f4f8' stroke='#2980b9' stroke-width='3' rx='4'/><text x='190' y='25' font-family='sans-serif' font-size='14' font-weight='bold' fill='currentColor' text-anchor='middle'>8 cm (length)</text><text x='315' y='85' font-family='sans-serif' font-size='13' font-weight='bold' fill='currentColor'>5 cm</text><text x='315' y='102' font-family='sans-serif' font-size='13' font-weight='bold' fill='currentColor'>(width)</text><text x='190' y='160' font-family='sans-serif' font-size='14' font-weight='bold' fill='currentColor' text-anchor='middle'>8 cm (length)</text><text x='15' y='85' font-family='sans-serif' font-size='13' font-weight='bold' fill='currentColor'>5 cm</text><text x='15' y='102' font-family='sans-serif' font-size='13' font-weight='bold' fill='currentColor'>(width)</text></svg><div class='worked-example'><h4>Example: Rectangle with length 8 and width 5</h4><p>Method 1: Add all sides = \\(8 + 5 + 8 + 5 = \\)<strong>26</strong></p><p>Method 2: Use formula = \\(2(8 + 5) = 2 \\times 13 = \\)<strong>26</strong></p><p>Method 3: Use formula = \\((2 \\times 8) + (2 \\times 5) = 16 + 10 = \\)<strong>26</strong></p></div>"
    },
    {
        "title": "Formula for Square Perimeter",
        "body": "<h3>The Square Formula</h3><p>A square is a special rectangle where <strong>ALL sides are equal</strong>. So the formula is even simpler:</p><div class='concept-box'><p><strong>Perimeter of Square = \\(4 \\times \\text{side}\\)</strong></p><p>Or: \\(P = 4s\\)</p></div><svg viewBox='0 0 310 260' xmlns='http://www.w3.org/2000/svg' style='margin: 20px 0; max-width: 310px; width: 100%;'><rect x='75' y='40' width='150' height='150' fill='#f9e79f' stroke='#f39c12' stroke-width='3' rx='4'/><text x='150' y='25' font-family='sans-serif' font-size='14' font-weight='bold' fill='currentColor' text-anchor='middle'>6 cm</text><text x='240' y='120' font-family='sans-serif' font-size='14' font-weight='bold' fill='currentColor'>6 cm</text><text x='150' y='210' font-family='sans-serif' font-size='14' font-weight='bold' fill='currentColor' text-anchor='middle'>6 cm</text><text x='15' y='120' font-family='sans-serif' font-size='14' font-weight='bold' fill='currentColor'>6 cm</text></svg><div class='worked-example'><h4>Example: Square with side 6 cm</h4><p>\\(P = 4 \\times 6 = \\)<strong>24 cm</strong></p><p>Check: \\(6 + 6 + 6 + 6 = 24\\) cm ✓</p></div><div class='success-box'><p><strong>Why the formula works:</strong> A square has 4 equal sides, so multiply one side by 4!</p></div>"
    },
    {
        "title": "Other Regular Shapes",
        "body": "<h3>Equilateral Triangle</h3><p>All three sides are equal, so multiply by 3:</p><div class='worked-example'><p><strong>Perimeter = \\(3 \\times \\text{side}\\)</strong> or \\(P = 3s\\)</p><p>Example: Side = 7 cm → \\(P = 3 \\times 7 = 21\\) cm</p></div><h3>Regular Pentagon</h3><p>All five sides are equal, so multiply by 5:</p><div class='worked-example'><p><strong>Perimeter = \\(5 \\times \\text{side}\\)</strong> or \\(P = 5s\\)</p><p>Example: Side = 4 m → \\(P = 5 \\times 4 = 20\\) m</p></div><h3>Regular Hexagon</h3><p>All six sides are equal, so multiply by 6:</p><div class='worked-example'><p><strong>Perimeter = \\(6 \\times \\text{side}\\)</strong> or \\(P = 6s\\)</p><p>Example: Side = 3 cm → \\(P = 6 \\times 3 = 18\\) cm</p></div><div class='concept-box'><p><strong>Pattern:</strong> For any regular polygon, Perimeter = (number of sides) × (one side length)</p></div>"
    },
    {
        "title": "Using Formulas in Real Problems",
        "body": "<h3>Problem Solving with Formulas</h3><div class='worked-example'><h4>Problem: A rectangular swimming pool is 12 metres long and 8 metres wide. You want to build a safety fence around it. How much fencing do you need?</h4><p>Use the rectangle formula:</p><p>\\(P = 2(l + w) = 2(12 + 8) = 2 \\times 20 = \\)<strong>40 metres</strong></p><p>You need 40 metres of fencing.</p></div><div class='worked-example'><h4>Problem: A square garden has sides of 15 metres. How much trim is needed for the edge?</h4><p>Use the square formula:</p><p>\\(P = 4s = 4 \\times 15 = \\)<strong>60 metres</strong></p><p>You need 60 metres of trim.</p></div><div class='warning-box'><p><strong>Always check:</strong> Make sure you're using the right formula (rectangle vs. square) and that your units match!</p></div>"
    }
]
