TITLE = "Collecting Data"

SECTIONS = [
    {
        "title": "Data is Everywhere",
        "body": "<div class='concept-box'><p>Every day you encounter <strong>data</strong>: test scores, temperatures, heights, favorite colors, social media likes. Raw data is just a pile of numbers or facts. <strong>Statistics</strong> gives us tools to make sense of it.</p><p><strong>Three key questions statistics answers:</strong></p><ul><li><strong>SUMMARIZE:</strong> What's typical? (mean, median, mode)</li><li><strong>SPREAD:</strong> How varied? (range, standard deviation)</li><li><strong>VISUALIZE:</strong> What patterns emerge? (graphs, diagrams)</li></ul></div><h3>Real Examples</h3><ul><li><strong>Test Scores:</strong> 12 students take a test. Are most scores high or low? One score way higher than the rest?</li><li><strong>Temperatures:</strong> Record daily highs for a month. How hot is it typically? When was the coldest day?</li><li><strong>Heights:</strong> Measure 20 students. What's the average? How much do heights vary?</li></ul>"
    },
    {
        "title": "Types of Data: Discrete vs. Continuous",
        "body": "<h3>Discrete Data: Counted, Not Measured</h3><p><strong>Discrete data</strong> comes from counting. It takes specific, separate values—usually whole numbers.</p><div class='example-box'><p><strong>Examples of discrete data:</strong></p><ul><li>Number of students in a class: 28 (not 28.5)</li><li>Goals scored in a match: 3 (not 3.7)</li><li>Shoe size: 5, 6, 7 (not 5.3)</li><li>Number of cars in a car park: 45 (not 45.2)</li></ul></div><h3>Continuous Data: Measured, Not Counted</h3><p><strong>Continuous data</strong> comes from measurement. It can take any value within a range (including decimals).</p><div class='example-box'><p><strong>Examples of continuous data:</strong></p><ul><li>Height of a person: 162.5 cm, 165.8 cm (can be any value)</li><li>Temperature: 23.6°C, 24.1°C (any value possible)</li><li>Time to run 100m: 12.34 seconds (any value possible)</li><li>Weight: 65.2 kg, 65.3 kg (any value between min and max)</li></ul></div><div class='success-box'><p><strong>Quick way to remember:</strong> Discrete = count (whole numbers). Continuous = measure (any value).</p></div>"
    },
    {
        "title": "Types of Data: Qualitative vs. Quantitative",
        "body": "<h3>Quantitative Data: Numbers We Can Measure</h3><p><strong>Quantitative data</strong> is numerical. We can add, subtract, and calculate with it.</p><div class='example-box'><p><strong>Examples of quantitative data:</strong></p><ul><li>Test scores: 78, 85, 92 (we can calculate mean)</li><li>Ages: 13, 14, 15 (we can find oldest and youngest)</li><li>Prices: £2.50, £3.00, £4.25 (we can find total cost)</li><li>Hours of sleep: 7, 8, 6 (we can calculate average)</li></ul></div><h3>Qualitative Data: Descriptions and Categories</h3><p><strong>Qualitative data</strong> is descriptive. It describes qualities or categories, not numbers.</p><div class='example-box'><p><strong>Examples of qualitative data:</strong></p><ul><li>Favorite color: red, blue, green</li><li>Eye color: brown, blue, green</li><li>Favorite food: pizza, pasta, salad</li><li>Weather: sunny, rainy, cloudy</li></ul></div><div class='success-box'><p><strong>Important:</strong> You can count qualitative data (how many chose red?), but you can't calculate mean or add qualitative values.</p></div>"
    },
    {
        "title": "Methods of Collecting Data",
        "body": "<h3>1. Survey (Questionnaire)</h3><p>Ask people questions. Examples: favorite color, hours of TV watched, satisfaction with school meals.</p><div class='example-box'><p><strong>Pros:</strong> Quick, inexpensive, can reach many people</p><p><strong>Cons:</strong> People might not answer honestly; hard to reach everyone</p></div><h3>2. Observation</h3><p>Watch and record without asking. Example: count how many cars pass a point in an hour; observe student behavior in the playground.</p><div class='example-box'><p><strong>Pros:</strong> Get real behavior, not what people say they do</p><p><strong>Cons:</strong> Time-consuming; observer might bias what they see</p></div><h3>3. Experiment</h3><p>Control conditions and measure outcomes. Example: test how height of a ramp affects distance a ball travels.</p><div class='example-box'><p><strong>Pros:</strong> Find cause and effect; reliable results</p><p><strong>Cons:</strong> Expensive; hard to replicate real-world conditions</p></div><h3>4. Existing Records</h3><p>Use data already collected. Example: school exam records, weather service temperature records, government census data.</p><div class='example-box'><p><strong>Pros:</strong> Free, large datasets available</p><p><strong>Cons:</strong> Might not be exactly what you need; may be outdated</p></div><div class='success-box'><p><strong>Key Point:</strong> The collection method affects data quality. Biased surveys give unreliable results. Good data comes from careful, unbiased collection.</p></div>"
    }
]
