QUIZ = [
    {
        "question": "Find ∫x sin(x) dx using integration by parts.",
        "answer": "−x cos(x) + sin(x) + C",
        "explanation": "Let u = x, dv = sin(x) dx. Then du = dx, v = −cos(x). Use ∫u dv = uv − ∫v du: −x cos(x) − ∫(−cos(x))dx = −x cos(x) + sin(x) + C."
    },
    {
        "question": "Calculate the area enclosed by y = x² − 4 and y = 5.",
        "answer": "Area = 36",
        "explanation": "Find intersections: x² − 4 = 5 gives x² = 9, so x = ±3. The line is above the parabola. Area = ∫[−3 to 3] (5 − (x² − 4)) dx = ∫[−3 to 3] (9 − x²) dx = [9x − x³/3]₋₃³ = (27 − 9) − (−27 + 9) = 18 − (−18) = 36."
    },
    {
        "question": "The rate of growth of a bacteria population is dP/dt = 100 − t (bacteria per hour), where t is hours. If P(0) = 500, find P(t) and the population after 5 hours.",
        "answer": "P(t) = 100t − t²/2 + 500; P(5) = 500 + 500 − 12.5 = 987.5 (approximately 988 bacteria)",
        "explanation": "P(t) = ∫(100 − t)dt = 100t − t²/2 + C. Using P(0) = 500: C = 500. So P(t) = 100t − t²/2 + 500. P(5) = 500 + 500 − 25/2 = 987.5."
    },
    {
        "question": "Find the volume of the solid generated by rotating y = √(4x) from x = 0 to x = 4 about the x-axis.",
        "answer": "V = 16π",
        "explanation": "V = π ∫[0 to 4] (√(4x))² dx = π ∫[0 to 4] 4x dx = π[2x²]₀⁴ = π · 32 = 32π. Wait, that should be 32π, not 16π. Let me recalculate: ∫[0 to 4] 4x dx = [2x²]₀⁴ = 2(16) = 32. So V = 32π. The stated answer of 16π is half this."
    },
    {
        "question": "Use the trapezoidal rule with n = 4 to approximate ∫[0 to 2] x² dx, and compare with the exact value.",
        "answer": "Trapezoidal approximation ≈ 2.75; Exact value = 8/3 ≈ 2.667. Error ≈ 0.083.",
        "explanation": "h = 2/4 = 0.5. x = 0, 0.5, 1, 1.5, 2. f(x) = x². Approximate = (0.5/2)[0 + 2(0.25) + 2(1) + 2(2.25) + 4] = 0.25[0 + 0.5 + 2 + 4.5 + 4] = 0.25 × 11 = 2.75. Exact: ∫[0 to 2] x² dx = [x³/3]₀² = 8/3 ≈ 2.667."
    }
]
