# Concept 3: Return Values and Scope

TITLE = "Return Values and Scope"

SECTIONS = [
    {
        "id": "py_functions_03_01",
        "title": "Understanding Return Statements",
        "body": '<div class="concept-box"><h4>What is a Return Value?</h4><p>The <code>return</code> statement sends a value back to the code that called the function. Without a return statement, functions return <code>None</code>.</p></div><div class="worked-example"><h4>Basic Return Example</h4><pre>def add(a, b):\n    result = a + b\n    return result  # Send the value back\n\nanswer = add(3, 5)\nprint(answer)  # Output: 8\n\ndef greet():\n    print("Hello!")\n    # No return statement, implicitly returns None\n\nvalue = greet()  # Output: Hello!\nprint(value)  # Output: None</pre></div><h3>Multiple Return Values</h3><p>You can return multiple values by returning a tuple.</p><div class="worked-example"><h4>Returning Multiple Values</h4><pre>def divide_with_remainder(a, b):\n    quotient = a // b\n    remainder = a % b\n    return quotient, remainder  # Returns a tuple\n\nq, r = divide_with_remainder(17, 5)\nprint(f"{q} remainder {r}")  # Output: 3 remainder 2</pre></div>'
    },
    {
        "id": "py_functions_03_02",
        "title": "Variable Scope: Local vs. Global",
        "body": '<h3>Local Scope</h3><p>Variables created inside a function are <strong>local</strong> to that function. They cannot be accessed outside the function.</p><div class="worked-example"><h4>Local Scope Example</h4><pre>def create_variable():\n    x = 10  # x is local to this function\n    print(x)  # Works: we are inside the function\n\ncreate_variable()  # Output: 10\nprint(x)  # Error: x does not exist outside the function</pre></div><h3>Global Scope</h3><p>Variables created at the module level (outside all functions) are <strong>global</strong>.</p><div class="worked-example"><h4>Global Scope Example</h4><pre>x = 100  # Global variable\n\ndef print_x():\n    print(x)  # Can access global x\n\nprint_x()  # Output: 100\nprint(x)  # Output: 100\n\ndef try_modify():\n    x = 50  # Creates a LOCAL x, does not modify global x\n    print(x)\n\ntry_modify()  # Output: 50\nprint(x)  # Output: 100 (global x unchanged)</pre></div><div class="warning-box"><h4>The global Keyword</h4><p>If you need to modify a global variable inside a function, use the <code>global</code> keyword. However, this is generally considered bad practice—use function returns instead.</p></div><div class="worked-example"><h4>Using global (Not Recommended)</h4><pre>x = 100\n\ndef modify_x():\n    global x  # Declare that we are modifying global x\n    x = 200\n    print(x)\n\nmodify_x()  # Output: 200\nprint(x)  # Output: 200</pre></div>'
    },
    {
        "id": "py_functions_03_03",
        "title": "Function Encapsulation and Data Privacy",
        "body": '<h3>Why Scope Matters</h3><div class="concept-box"><h4>Benefits of Local Scope</h4><ul><li><strong>Encapsulation:</strong> Hide implementation details inside functions</li><li><strong>No name conflicts:</strong> Different functions can have variables with the same name</li><li><strong>Predictability:</strong> Functions are self-contained and easier to understand</li><li><strong>Safety:</strong> Accidental modifications are prevented</li></ul></div><h3>Scope Hierarchy: LEGB Rule</h3><p>Python looks for variables in this order:</p><ol><li><strong>L</strong>ocal: Inside the current function</li><li><strong>E</strong>nclosing: In outer functions (for nested functions)</li><li><strong>G</strong>lobal: At module level</li><li><strong>B</strong>uilt-in: Python built-in names</li></ol><div class="worked-example"><h4>Scope Hierarchy in Action</h4><pre>x = "global"  # Global scope\n\ndef outer():\n    x = "enclosing"  # Enclosing scope\n\n    def inner():\n        x = "local"  # Local scope\n        print(x)\n\n    inner()  # Output: local\n    print(x)  # Output: enclosing\n\nouter()\nprint(x)  # Output: global</pre></div><h3>Nested Functions and Closures</h3><p>Inner functions can access variables from outer functions, creating a closure.</p><div class="success-box"><h4>Closure Example</h4><pre>def outer(x):\n    def inner():\n        print(f"x from outer: {x}")\n\n    return inner\n\nfunc = outer(42)\nfunc()  # Output: x from outer: 42</pre></div>'
    },
    {
        "id": "py_functions_03_04",
        "title": "Early Returns and Function Flow Control",
        "body": '<h3>Using Return to Exit Early</h3><p>The <code>return</code> statement immediately exits the function, making it useful for control flow.</p><div class="worked-example"><h4>Early Return Example</h4><pre>def validate_age(age):\n    if age < 0:\n        return "Age cannot be negative"\n    if age < 18:\n        return "Must be 18 or older"\n    return "Valid age"\n\nprint(validate_age(-5))  # Output: Age cannot be negative\nprint(validate_age(15))  # Output: Must be 18 or older\nprint(validate_age(25))  # Output: Valid age</pre></div><h3>Guard Clauses</h3><p>Use early returns for invalid cases to reduce nesting and improve readability.</p><div class="success-box"><h4>Guard Clause Pattern</h4><pre># Without guard clauses (nested and hard to read)\ndef process_data(data):\n    if data is not None:\n        if isinstance(data, list):\n            if len(data) > 0:\n                return sum(data) / len(data)\n    return None\n\n# With guard clauses (clear and readable)\ndef process_data(data):\n    if data is None:\n        return None\n    if not isinstance(data, list):\n        return None\n    if len(data) == 0:\n        return None\n    return sum(data) / len(data)</pre></div>'
    }
]
