# Concept 4: Lambda and Higher-Order Functions

TITLE = "Lambda and Higher-Order Functions"

SECTIONS = [
    {
        "id": "py_functions_04_01",
        "title": "Lambda Functions: Anonymous Functions",
        "body": '<div class="concept-box"><h4>What is a Lambda Function?</h4><p>A lambda function is a small anonymous function defined with the <code>lambda</code> keyword. It can have any number of parameters but only one expression.</p></div><h3>Lambda Syntax</h3><p><code>lambda arguments: expression</code></p><div class="worked-example"><h4>Lambda Function Examples</h4><pre># Simple lambda\nsquare = lambda x: x ** 2\nprint(square(5))  # Output: 25\n\n# Lambda with multiple parameters\nadd = lambda x, y: x + y\nprint(add(3, 4))  # Output: 7\n\n# Lambda with default parameters\ngreet = lambda name="World": f"Hello, {name}!"\nprint(greet())  # Output: Hello, World!\nprint(greet("Alice"))  # Output: Hello, Alice!</pre></div><h3>When to Use Lambda</h3><p>Lambda functions are best for short, simple operations. For complex logic, use regular functions.</p><div class="success-box"><h4>Good Use Cases for Lambda</h4><ul><li>As arguments to higher-order functions like <code>map()</code>, <code>filter()</code>, <code>sorted()</code></li><li>Simple one-off functions you will not reuse</li><li>Quick data transformations</li></ul></div><div class="warning-box"><h4>When NOT to Use Lambda</h4><p>Do not use lambda for complex logic. It becomes unreadable quickly. Use regular functions instead.</p></div>'
    },
    {
        "id": "py_functions_04_02",
        "title": "Higher-Order Functions: Functions as Arguments",
        "body": '<h3>Functions as First-Class Objects</h3><p>In Python, functions are objects. You can pass them as arguments, return them from functions, and store them in variables.</p><div class="worked-example"><h4>Functions as Arguments</h4><pre>def apply_operation(a, b, operation):\n    """Apply an operation to two numbers."""\n    return operation(a, b)\n\nadd = lambda x, y: x + y\nmultiply = lambda x, y: x * y\n\nprint(apply_operation(5, 3, add))  # Output: 8\nprint(apply_operation(5, 3, multiply))  # Output: 15</pre></div><h3>map(): Transform Data</h3><p>The <code>map()</code> function applies a function to each element in an iterable.</p><div class="worked-example"><h4>Using map()</h4><pre>numbers = [1, 2, 3, 4, 5]\n\n# Double each number\ndoubled = list(map(lambda x: x * 2, numbers))\nprint(doubled)  # Output: [2, 4, 6, 8, 10]\n\n# Or with a regular function\ndef double(x):\n    return x * 2\n\ndoubled = list(map(double, numbers))\nprint(doubled)  # Output: [2, 4, 6, 8, 10]</pre></div><h3>filter(): Select Data</h3><p>The <code>filter()</code> function keeps only elements where the function returns True.</p><div class="worked-example"><h4>Using filter()</h4><pre>numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\n\n# Keep only even numbers\nevens = list(filter(lambda x: x % 2 == 0, numbers))\nprint(evens)  # Output: [2, 4, 6, 8, 10]\n\n# Keep only numbers greater than 5\nlarge = list(filter(lambda x: x > 5, numbers))\nprint(large)  # Output: [6, 7, 8, 9, 10]</pre></div>'
    },
    {
        "id": "py_functions_04_03",
        "title": "Sorting with Custom Functions",
        "body": '<h3>sorted() with Key Functions</h3><p>The <code>sorted()</code> function key parameter accepts a function that extracts a comparison value.</p><div class="worked-example"><h4>Sorting with Lambda</h4><pre>students = [\n    {"name": "Alice", "grade": 85},\n    {"name": "Bob", "grade": 92},\n    {"name": "Carol", "grade": 78}\n]\n\n# Sort by grade\nby_grade = sorted(students, key=lambda s: s["grade"])\nfor student in by_grade:\n    print(f"{student[\"name\"]}: {student[\"grade\"]}")\n\n# Output:\n# Carol: 78\n# Alice: 85\n# Bob: 92\n\n# Sort by name (reverse alphabetical)\nby_name = sorted(students, key=lambda s: s["name"], reverse=True)</pre></div><div class="worked-example"><h4>Sorting Strings by Custom Criteria</h4><pre>words = ["apple", "pie", "car", "book"]\n\n# Sort by length\nby_length = sorted(words, key=lambda w: len(w))\nprint(by_length)  # Output: ["pie", "car", "book", "apple"]\n\n# Sort by last character\nby_last_char = sorted(words, key=lambda w: w[-1])\nprint(by_last_char)  # Output: ["apple", "pie", "book", "car"]</pre></div>'
    },
    {
        "id": "py_functions_04_04",
        "title": "Returning Functions from Functions",
        "body": '<h3>Functions That Return Functions</h3><p>A function can return another function, enabling powerful functional programming patterns.</p><div class="worked-example"><h4>Function Factory</h4><pre>def make_multiplier(n):\n    """Return a function that multiplies by n."""\n    def multiplier(x):\n        return x * n\n    return multiplier\n\n# Create specialized functions\ndouble = make_multiplier(2)\ntriple = make_multiplier(3)\n\nprint(double(5))  # Output: 10\nprint(triple(5))  # Output: 15</pre></div><h3>Composition and Chaining</h3><p>You can combine functions to create more complex operations.</p><div class="worked-example"><h4>Function Composition</h4><pre>def compose(f, g):\n    """Compose two functions: (f ∘ g)(x) = f(g(x))."""\n    return lambda x: f(g(x))\n\ndouble = lambda x: x * 2\nadd_one = lambda x: x + 1\n\n# Apply add_one, then double\nadd_then_double = compose(double, add_one)\nprint(add_then_double(5))  # Output: 12 (5+1=6, 6*2=12)</pre></div><div class="success-box"><h4>Real-World Example: Data Pipeline</h4><pre>def pipeline(*functions):\n    """Apply multiple functions in sequence."""\n    def apply(x):\n        for func in functions:\n            x = func(x)\n        return x\n    return apply\n\n# Define transformations\nremove_spaces = lambda s: s.replace(" ", "")\nuppercase = lambda s: s.upper()\nadd_prefix = lambda s: "PREFIX_" + s\n\n# Combine them\ntransform = pipeline(remove_spaces, uppercase, add_prefix)\nresult = transform("hello world")\nprint(result)  # Output: PREFIX_HELLOWORLD</pre></div>'
    }
]
